In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../Resources/whatoplay_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1195 entries, 0 to 1194
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             1195 non-null   object
 1   Platform         1195 non-null   object
 2   Year_of_Release  1195 non-null   int64
 3   Genre            1195 non-null   object
 4   Publisher        1195 non-null   object
 5   NA_Sales         1195 non-null   float64
 6   EU_Sales         1195 non-null   float64
 7   JP_Sales         1195 non-null   float64
 8   Other_Sales      1195 non-null   float64
 9   Global_Sales     1195 non-null   float64
 10  Critic_Score     1195 non-null   int64
 11  Critic_Count     1195 non-null   int64
 12  User_Score       1195 non-null   float64
 13  User_Count       1195 non-null   int64
 14  Developer        1195 non-null   object
 15  Rating           1195 non-null   object
 16  PlayScore        1195 non-null   float64
 17  GameScore        1195 non-null   float64
 18  CriticScore      1195 non-null   float64
dtypes: float64(9), int64(4), object(6)
memory usage: 177.5+ KB

In [3]:
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,PlayScore,GameScore,CriticScore
0,Grand Theft Auto V,PS3,2013,Action,Take-Two Interactive,7.02,9.09,0.98,3.96,21.04,97,50,8.2,3994,Rockstar North,M,9.29,9.34,9.24
1,Call of Duty: Black Ops II,PS3,2012,Shooter,Activision,4.99,5.73,0.65,2.42,13.79,83,21,5.3,922,Treyarch,M,7.73,7.52,7.95
2,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,5.54,5.73,0.49,1.57,13.32,88,39,3.2,5234,"Infinity Ward, Sledgehammer Games",M,8.00,7.56,8.44
3,Mario Kart 7,3DS,2011,Racing,Nintendo,5.03,4.02,2.69,0.91,12.66,85,73,8.2,632,"Retro Studios, Entertainment Analysis & Develo...",E,9.09,9.77,8.41
4,Call of Duty: Black Ops,PS3,2010,Shooter,Activision,5.99,4.37,0.48,1.79,12.63,88,58,6.4,1094,Treyarch,M,8.16,7.91,8.41

In [4]:

bins = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
labels = ["11", "10","9", "8", "7", "6", "5", "4", "3", "2", "1"]
df['GlobalSellers'] = pd.cut(df['Global_Sales'], bins=bins, labels=labels)

In [5]:
df['Global_Sales'].describe()

count    1195.000000
mean        0.917556
std         1.716844
min         0.010000
25%         0.100000
50%         0.360000
75%         0.940000
max        21.040000
Name: Global_Sales, dtype: float64

In [6]:
bins = [0, 0.94, 22]
labels = ["Not Top Seller", "Top Seller"]
df['TopSellers'] = pd.cut(df['Global_Sales'], bins=bins, labels=labels)
df

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,...,Critic_Count,User_Score,User_Count,Developer,Rating,PlayScore,GameScore,CriticScore,GlobalSellers,TopSellers
0,Grand Theft Auto V,PS3,2013,Action,Take-Two Interactive,7.02,9.09,0.98,3.96,21.04,...,50,8.2,3994,Rockstar North,M,9.29,9.34,9.24,1,Top Seller
1,Call of Duty: Black Ops II,PS3,2012,Shooter,Activision,4.99,5.73,0.65,2.42,13.79,...,21,5.3,922,Treyarch,M,7.73,7.52,7.95,5,Top Seller
2,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,5.54,5.73,0.49,1.57,13.32,...,39,3.2,5234,"Infinity Ward, Sledgehammer Games",M,8.00,7.56,8.44,5,Top Seller
3,Mario Kart 7,3DS,2011,Racing,Nintendo,5.03,4.02,2.69,0.91,12.66,...,73,8.2,632,"Retro Studios, Entertainment Analysis & Develo...",E,9.09,9.77,8.41,5,Top Seller
4,Call of Duty: Black Ops,PS3,2010,Shooter,Activision,5.99,4.37,0.48,1.79,12.63,...,58,6.4,1094,Treyarch,M,8.16,7.91,8.41,5,Top Seller
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,Alone in the Dark,PC,2008,Adventure,Atari,0.00,0.01,0.00,0.00,0.01,...,19,5.7,148,Eden Studios,M,6.02,5.66,6.38,11,Not Top Seller
1191,Clive Barker's Jericho,PC,2007,Shooter,Codemasters,0.00,0.01,0.00,0.00,0.01,...,25,7.5,218,"Mercury Steam, Alchemic Productions",M,7.04,7.38,6.71,11,Not Top Seller
1192,Transformers: Fall of Cybertron,PC,2012,Action,Activision,0.01,0.00,0.00,0.00,0.01,...,13,7.9,121,"High Moon Studios, Mercenary Technologies",T,8.39,8.98,7.80,11,Not Top Seller
1193,Trine,PC,2009,Action,Nobilis,0.00,0.01,0.00,0.00,0.01,...,50,8.2,488,"Frozenbyte, Inc.",E10+,8.61,9.34,7.87,11,Not Top Seller
1194,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,...,20,7.6,412,Kojima Productions,M,7.98,8.16,7.79,11,Not Top Seller

In [7]:
df['Critic_Score'].describe()

count    1195.000000
mean       75.101255
std        11.547975
min        26.000000
25%        69.000000
50%        77.000000
75%        83.000000
max        98.000000
Name: Critic_Score, dtype: float64

In [8]:
bins = [0, 83, 100]
labels = ["Less", "TopRated"]
df['TopRated'] = pd.cut(df['Critic_Score'], bins=bins, labels=labels)
df

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,...,User_Score,User_Count,Developer,Rating,PlayScore,GameScore,CriticScore,GlobalSellers,TopSellers,TopRated
0,Grand Theft Auto V,PS3,2013,Action,Take-Two Interactive,7.02,9.09,0.98,3.96,21.04,...,8.2,3994,Rockstar North,M,9.29,9.34,9.24,1,Top Seller,TopRated
1,Call of Duty: Black Ops II,PS3,2012,Shooter,Activision,4.99,5.73,0.65,2.42,13.79,...,5.3,922,Treyarch,M,7.73,7.52,7.95,5,Top Seller,Less
2,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,5.54,5.73,0.49,1.57,13.32,...,3.2,5234,"Infinity Ward, Sledgehammer Games",M,8.00,7.56,8.44,5,Top Seller,TopRated
3,Mario Kart 7,3DS,2011,Racing,Nintendo,5.03,4.02,2.69,0.91,12.66,...,8.2,632,"Retro Studios, Entertainment Analysis & Develo...",E,9.09,9.77,8.41,5,Top Seller,TopRated
4,Call of Duty: Black Ops,PS3,2010,Shooter,Activision,5.99,4.37,0.48,1.79,12.63,...,6.4,1094,Treyarch,M,8.16,7.91,8.41,5,Top Seller,TopRated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,Alone in the Dark,PC,2008,Adventure,Atari,0.00,0.01,0.00,0.00,0.01,...,5.7,148,Eden Studios,M,6.02,5.66,6.38,11,Not Top Seller,Less
1191,Clive Barker's Jericho,PC,2007,Shooter,Codemasters,0.00,0.01,0.00,0.00,0.01,...,7.5,218,"Mercury Steam, Alchemic Productions",M,7.04,7.38,6.71,11,Not Top Seller,Less
1192,Transformers: Fall of Cybertron,PC,2012,Action,Activision,0.01,0.00,0.00,0.00,0.01,...,7.9,121,"High Moon Studios, Mercenary Technologies",T,8.39,8.98,7.80,11,Not Top Seller,Less
1193,Trine,PC,2009,Action,Nobilis,0.00,0.01,0.00,0.00,0.01,...,8.2,488,"Frozenbyte, Inc.",E10+,8.61,9.34,7.87,11,Not Top Seller,Less
1194,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,...,7.6,412,Kojima Productions,M,7.98,8.16,7.79,11,Not Top Seller,Less

In [9]:
data = df

In [81]:
# Coding strings

In [10]:
#Extracting values to be encoded

name = data["Name"].values
platform = data["Platform"].values
genre = data["Genre"].values
publisher = data["Publisher"].values
developer = data["Developer"].values
rating = data["Rating"].values
critic_score = data["Critic_Score"].values
critic_count = data["Critic_Count"].values
top_rated = data["TopRated"].values
top_sellers = data["TopSellers"].values
global_sellers = data["GlobalSellers"].values

In [11]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_encoder.fit(name)
coded_name = label_encoder.transform(name)

label_encoder.fit(platform)
coded_platform = label_encoder.transform(platform)

label_encoder.fit(genre)
coded_genre = label_encoder.transform(genre)

label_encoder.fit(publisher)
coded_publisher = label_encoder.transform(publisher)

label_encoder.fit(developer)
coded_developer = label_encoder.transform(developer)

label_encoder.fit(rating)
coded_rating = label_encoder.transform(rating)

label_encoder.fit(critic_score)
coded_critic_score = label_encoder.transform(critic_score)

label_encoder.fit(critic_count)
coded_critic_count = label_encoder.transform(critic_count)

label_encoder.fit(top_sellers)
coded_top_sellers = label_encoder.transform(top_sellers)

label_encoder.fit(top_rated)
coded_top_rated = label_encoder.transform(top_rated)

label_encoder.fit(global_sellers)
coded_global_sellers = label_encoder.transform(global_sellers)

In [12]:
# Checking out the encoded Top Ranked column

print("Uncoded 'TopRated' output: ")
print(data["TopRated"])
print("----------------------------------------------")
print("Coded 'TopRated' output: ")
print(coded_top_rated)

Uncoded 'TopRated' output:
0       TopRated
1           Less
2       TopRated
3       TopRated
4       TopRated
          ...
1190        Less
1191        Less
1192        Less
1193        Less
1194        Less
Name: TopRated, Length: 1195, dtype: category
Categories (2, object): [Less < TopRated]
----------------------------------------------
Coded 'TopRated' output:
[1 0 1 ... 0 0 0]

In [13]:
#Making a fully coded dataset called features to run machine learning

features = data.copy()
features['Name'] = coded_name
features['Platform'] = coded_platform
features['Genre'] = coded_genre
features['Publisher'] = coded_publisher
features['Developer'] = coded_developer
features['Rating'] = coded_rating
features['Critic_Score'] = coded_critic_score
features['Critc_Count'] = coded_critic_count
features['TopSellers'] = coded_top_sellers
features['TopRated'] = coded_top_rated
features['GlobalSellers'] = coded_global_sellers
features

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,...,User_Count,Developer,Rating,PlayScore,GameScore,CriticScore,GlobalSellers,TopSellers,TopRated,Critc_Count
0,323,2,2013,0,81,7.02,9.09,0.98,3.96,21.04,...,3994,303,2,9.29,9.34,9.24,0,1,1,46
1,109,2,2012,8,3,4.99,5.73,0.65,2.42,13.79,...,922,380,2,7.73,7.52,7.95,3,1,0,17
2,113,2,2011,8,3,5.54,5.73,0.49,1.57,13.32,...,5234,184,2,8.00,7.56,8.44,3,1,1,35
3,457,0,2011,6,56,5.03,4.02,2.69,0.91,12.66,...,632,300,0,9.09,9.77,8.41,3,1,1,69
4,108,2,2010,8,3,5.99,4.37,0.48,1.79,12.63,...,1094,380,2,8.16,7.91,8.41,3,1,1,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,17,1,2008,1,10,0.00,0.01,0.00,0.00,0.01,...,148,114,2,6.02,5.66,6.38,2,0,0,15
1191,127,1,2007,8,17,0.00,0.01,0.00,0.00,0.01,...,218,227,2,7.04,7.38,6.71,2,0,0,21
1192,870,1,2012,0,3,0.01,0.00,0.00,0.00,0.01,...,121,175,3,8.39,8.98,7.80,2,0,0,9
1193,872,1,2009,0,58,0.00,0.01,0.00,0.00,0.01,...,488,144,1,8.61,9.34,7.87,2,0,0,46
1194,481,1,2014,0,42,0.00,0.01,0.00,0.00,0.01,...,412,199,2,7.98,8.16,7.79,2,0,0,16

In [14]:
MLdata = pd.DataFrame(features)

In [15]:
MLdata.to_csv('MLdata.csv')